using Microsoft.EntityFrameworkCore;

namespace Baseport;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<TableDefinition> Tables => Set<TableDefinition>();
    public DbSet<FieldDefinition> Fields => Set<FieldDefinition>();
    public DbSet<FormConfig> FormConfigs => Set<FormConfig>();
    public DbSet<Record> Records => Set<Record>();
    public DbSet<UserAccount> UserAccounts => Set<UserAccount>();
    public DbSet<UserSession> UserSessions => Set<UserSession>();
    public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
    public DbSet<SavedQuery> SavedQueries => Set<SavedQuery>();
    public DbSet<AppSettings> AppSettings => Set<AppSettings>();
    public DbSet<JobConfig> JobConfigs => Set<JobConfig>();
    public DbSet<OidcProvider> OidcProviders => Set<OidcProvider>();

    // Settings are a single row. Ordered so EF does not warn that an unordered First could return anything.
    public Task<AppSettings?> SettingsAsync() =>
        AppSettings.OrderBy(s => s.Id).FirstOrDefaultAsync();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Every table in this database is a system table: user data is rows in _records, never its own table.
        modelBuilder.Entity<TableDefinition>().ToTable("_tables");
        modelBuilder.Entity<FieldDefinition>().ToTable("_fields");
        modelBuilder.Entity<Record>().ToTable("_records");
        modelBuilder.Entity<FormConfig>().ToTable("_forms");
        modelBuilder.Entity<UserAccount>().ToTable("_users");
        modelBuilder.Entity<UserSession>().ToTable("_user_sessions");
        modelBuilder.Entity<AuditLog>().ToTable("_audit_log");
        modelBuilder.Entity<SavedQuery>().ToTable("_queries");
        modelBuilder.Entity<AppSettings>().ToTable("_settings");
        modelBuilder.Entity<JobConfig>().ToTable("_jobs");
        modelBuilder.Entity<OidcProvider>().ToTable("_oidc_providers");

        // Every relation keys on the unguessable id, because that is the only key these rows have.
        modelBuilder.Entity<TableDefinition>()
            .HasMany(t => t.Fields)
            .WithOne()
            .HasForeignKey(f => f.TableId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<FormConfig>()
            .HasOne<TableDefinition>()
            .WithMany()
            .HasForeignKey(f => f.TableId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<Record>()
            .HasOne<TableDefinition>()
            .WithMany()
            .HasForeignKey(r => r.TableId)
            .OnDelete(DeleteBehavior.Cascade);

        // A job is addressed by the name of the thing it does, not by a generated id: there is exactly one log cleanup, and it keeps its identity across a rebuild of the database.
        modelBuilder.Entity<JobConfig>().HasKey(j => j.Key);

        // Ids are generated by Ids.NewShortId on insert, never by the database.
        foreach (var entity in new[]
                 {
                     modelBuilder.Entity<TableDefinition>().Metadata,
                     modelBuilder.Entity<FieldDefinition>().Metadata,
                     modelBuilder.Entity<FormConfig>().Metadata,
                     modelBuilder.Entity<Record>().Metadata,
                     modelBuilder.Entity<UserAccount>().Metadata,
                     modelBuilder.Entity<UserSession>().Metadata,
                     modelBuilder.Entity<SavedQuery>().Metadata,
                     modelBuilder.Entity<AuditLog>().Metadata,
                     modelBuilder.Entity<OidcProvider>().Metadata
                 })
        {
            entity.FindProperty(nameof(TableDefinition.Id))!.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
        }

        // Id is in the index because it is the ORDER BY tiebreaker: without it SQLite cannot walk the index for a page and sorts the whole table instead.
        modelBuilder.Entity<Record>()
            .HasIndex(r => new { r.TableId, r.CreatedAt, r.Id });

        modelBuilder.Entity<UserAccount>().HasIndex(u => u.Username).IsUnique();

        // Every API request looks a token up by its hash, so it is indexed.
        modelBuilder.Entity<UserAccount>()
            .HasIndex(u => u.ApiTokenHash)
            .IsUnique()
            .HasFilter("\"ApiTokenHash\" <> ''");

        modelBuilder.Entity<OidcProvider>().HasIndex(p => p.Slug).IsUnique();

        // One provider identity maps to at most one account, or a second sign-in would have two accounts to choose between.
        modelBuilder.Entity<UserAccount>()
            .HasIndex(u => new { u.OidcProviderId, u.OidcSubject })
            .IsUnique()
            .HasFilter("\"OidcSubject\" <> ''");

        modelBuilder.Entity<UserSession>().HasIndex(s => s.RefreshTokenHash).IsUnique();
        modelBuilder.Entity<UserSession>().HasIndex(s => s.UserId);

        modelBuilder.Entity<UserSession>()
            .HasOne<UserAccount>()
            .WithMany()
            .HasForeignKey(s => s.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
