<Project>

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.0.1-alpha.12</Version>
    <Authors>Baseport</Authors>
    <Company>Melosso</Company>
    <Product>Baseport</Product>
    <Copyright>Copyright © Baseport $([System.DateTime]::Now.Year)</Copyright>
    <RepositoryUrl>https://github.com/baseporteu/baseport</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/baseporteu/baseport</PackageProjectUrl>
    <PackageLicenseExpression>EUPL-1.2</PackageLicenseExpression>
  </PropertyGroup>

</Project>
